version: '2'
services:

  demo:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    command: ./docker/cmd-webserver.sh
    env_file: ./docker/.env
    ports: ["9000:9000"]
    restart: "always"
