version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "setup.py" }}
      - run:
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            make install_requirements
      - save_cache:
          key: v1-deps-{{ checksum "setup.py" }}
          paths:
            - "venv"
      - run:
          command: |
            . .venv/bin/activate
            make pytest -- --cov=. --cov-config=.coveragerc --cov-report=html
            codecov

  flake8:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run:
          name: Run flake8
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flake8
            make flake8

  deploy_to_dev:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            make test_requirements
            make publish

workflows:
  version: 2
  test_and_deploy_to_dev:
    jobs:
      - flake8
      - test
      - deploy_to_dev:
          requires:
            - flake8
            - test
          filters:
            branches:
              only: master
